nodeLinker: hoisted

packages:
  - 'packages/*'
allowBuilds:
  '@firebase/util': set this to true or false
  '@prisma/client': true
  '@prisma/engines': set this to true or false
  esbuild: set this to true or false
  prisma: true
  protobufjs: set this to true or false
approvedBuilds: '@prisma/client'
